package com.example.art.model.enums;

public enum DealSubject {

    CREATED_DEAL,
    UPDATED_DEAL_PRODUCT_DETAILS,
    UPDATED_DEAL_COMMON_DETAILS,
    UPDATED_DEAL_ADDITIONAL_DETAILS,
    UPDATED_DEAL_AUTHORIZATION,
    ADDED_DEAL_CONTACT,
    DELETED_DEAL_CONTACT,
    ADDED_DEAL_CONSULTANT,
    DELETED_DEAL_CONSULTANT,
    ADDED_DEAL_INTERACTION,
    DELETED_DEAL_INTERACTION,
    UPDATED_DEAL_INTERACTION,
    SENT_DEAL_QUERY,
    ADDED_DEAL_ATTACHMENT,
    DELETED_DEAL_ATTACHMENT,

}
